name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

# github actions操作権限
permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.10.0
  AWS_REGION: ap-northeast-1
  TF_PROJECT: cicd-practice
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - name: 1.Checkout Repository
        uses: actions/checkout@v6
      - name: 2.Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: 3.Terraform fmt
        run: |
          terraform fmt -check
      - name: 4.Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: 5.Terraform init
        run: |
          terraform init -no-color
      - name: 6.Terraform Validate
        run: |
          terraform validate -no-color
      - name: 7.Terraform Plan
        run: |
          terraform plan \
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'environment=${{ env.TF_ENVIRONMENT }}' \
            -var 'username=${{ secrets.MYSQL_USERNAME }}' \
            -var 'password=${{ secrets.MYSQL_PASSWORD }}' \
            -input=false \
            -no-color \
            -detailed-exitcode
      # - name: 8.Slack Notify