# CICDのうち、CIを記述してコードのチェックなどを行う
name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

# github actions操作権限
permissions:
  id-token: write
  contents: read

# 変数
env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.10.0
  TF_PROJECT: cicd-practice
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:

      # --- Setup Phase ---
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      - name: tf setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      # --- Validate Phase ---
      - name: tf fmt
        run: |
          terraform fmt -check

      - name: tf init
        run: |
          terraform init -no-color

      - name: tf validate
        run: |
          terraform validate -no-color

      # --- Plan Phase ---
      - name: tf plan
        run: |
          terraform plan \
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'environment=${{ env.TF_ENVIRONMENT }}' \
            -var 'username=${{ secrets.MYSQL_USERNAME }}' \
            -var 'password=${{ secrets.MYSQL_PASSWORD }}' \
            -input=false \
            -no-color \
            -detailed-exitcode
      # - name: 8.Slack Notify